import { icon_manager } from "./icons.js";
import { overlay_manager } from "./overlay.js";
import { py_api } from "./py_api.js";
import { TitleBar } from "./title_bar.js";
import { toolbox } from "./toolbox.js";
import { layout_selector, series_selector, timeframe_selector, topbar } from "./topbar.js";
import { Container_Layouts } from "./util.js";
import { Wrapper } from "./wrapper.js";
window.api = new py_api();
window.svgs = new icon_manager();
window.wrapper = new Wrapper();
window.overlay_manager = new overlay_manager();
window.series_selector = new series_selector();
window.layout_selector = new layout_selector();
window.timeframe_selector = new timeframe_selector();
window.topbar = new topbar(window.wrapper, window.timeframe_selector, window.layout_selector, window.series_selector);
window.toolbox = new toolbox(window.wrapper);
window.titlebar = new TitleBar(window.wrapper);
window.Container_Layouts = Container_Layouts;
window.wrapper.resize();
window.loaded = true;
